databases:
  - name: flavorxplorer
    databaseName: flavorxplorer
    user: maddox
    plan: free

services:
  - type: web
    name: flavorxplorer
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flavorxplorer
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false